### ISSUE TITLE
Interaction

### ISSUE THREAD

**Issue by monfera** [maptime-ams/animated-borders-d3js#2]
I used the year slider here on the linked page and nothing seemed to happen: http://maptime-ams.github.io/animated-borders-d3js/tutorial/12/

When changing /12/ to /13/ I got to it. Just mentioning in case you wanted to update to that link directly.

**Comment by bertspaan** [comment]
This is on purpose: https://github.com/maptime-ams/animated-borders-d3js#step-12-time-slider

Only in step 13, the `change` event is added to the slider, and the map will update when the slider is used.
